services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasklib
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3326:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: